### ISSUE TITLE
3-unzip/2-htigs/split FileNotFoundError (2-asm-falcon/p_ctg.fa.fai)

### ISSUE THREAD

**Issue by clsaetre** [PacificBiosciences/pbbioconda#183]
**Operating system**
CentOS 6.10

**Package name**
falcon-unzip 1.3.4
falcon-kit 1.4.4
pypeflow 2.3.0

I ran conda update --all less than a week ago. 

**Conda environment**

```
# packages in environment at /usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bedtools                  2.28.0               hdf88d34_0    bioconda
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
falcon-kit                1.4.4                    pypi_0    pypi
falcon-phase              1.1.0                    pypi_0    pypi
falcon-unzip              1.3.4                    pypi_0    pypi
future                    0.17.1                py37_1000    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.17.1           py37h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pb-assembly               0.0.6                    py37_5    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.3.4            py37hed50d52_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.3                h33d41f4_1    conda-forge
python-edlib              1.3.4            py37hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py37h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
racon                     1.4.3                he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.2.0                   py37_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
```

**Describe the bug**
Falcon (fc_run) ran successfully, but I've been having trouble running Falcon-unzip (fc_unzip.py). My first run stopped at 3-unzip/reads, and after reading through some of the previously submitted issues I decided to replace mode = 'r' to mode = 'rt' under open_fasta_reader in FastaReader.py. I also ran conda update --all. My second run has now stopped at 3-unzip/2-htigs/split, and the error seems to be that it cannot find the file p_ctg.fa.fai in 2-asm-falcon. Could my "fixes" to the first problem have caused the second problem?

**Error message**

Here is the end of the falcon_unzip.err file:

```
[INFO]About to submit: Node(3-unzip/2-htigs/split)
[INFO]Popen: '/bin/bash -c "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pwatcher/mains/job_start.sh" > "/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/run-P5d086c1c3f99ae.bash.stdout" 2> "/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/run-P5d086c1c3f99ae.bash.stderr"'
[INFO](slept for another 161.0s -- another 21 loop iterations)
[INFO](slept for another 34.10000000000001s -- another 22 loop iterations)
[ERROR]Task Node(3-unzip/2-htigs/split) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(3-unzip/2-htigs/split)}
[ERROR]ready: set()
	submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
[ERROR]Error for run(target=clr, config_fn=fc_unzip_local.cfg, logging_config_fn=None)
Traceback (most recent call last):
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
    unzip_all(config, unzip_config_fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 542, in run_workflow
    run_script=TASK_GTOH_APPLY_UNITS_OF_WORK,
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_kit/pype.py", line 109, in gen_parallel_tasks
    wf.refreshTargets()
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(3-unzip/2-htigs/split)}
Traceback (most recent call last):
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.3.4', 'console_scripts', 'fc_unzip.py')()
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/mains/start_unzip.py", line 33, in main
    unzip.run(**vars(args))
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
    unzip_all(config, unzip_config_fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 542, in run_workflow
    run_script=TASK_GTOH_APPLY_UNITS_OF_WORK,
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_kit/pype.py", line 109, in gen_parallel_tasks
    wf.refreshTargets()
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(3-unzip/2-htigs/split)}
```

Here is part of the file 3-unzip/2-htigs/split/run-P5d086c1c3f99ae.bash.stderr:

```
[INFO 2019-09-01 22:38:00] Done loading sg_edges_list.
Traceback (most recent call last):
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1693, in <module>
    main()
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1689, in main
    args.func(args)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1510, in cmd_split
    top.fai2ctgs(falcon_p_ctg_fai_fn, '3-unzip/2-htigs/split/p_ctg_names.json')
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_unzip/tasks/top.py", line 16, in fai2ctgs
    with open(p_ctg_fai_fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../../2-asm-falcon/p_ctg.fa.fai'
2019-09-01 22:38:02,979 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-09-01 22:38:02,980 - root - INFO - CD: '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split' -> '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split'
2019-09-01 22:38:02,981 - root - INFO - CD: '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split' -> '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split'
2019-09-01 22:38:02,982 - root - CRITICAL - Error in /usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
```

**To Reproduce**
I'm not sure what you would need to reproduce this, so please let me know if there is anything else I should submit. Thank you so much in advance!

Best regards,
Camilla

**Comment by pb-cdunn** [comment]
ls -larth 3-unzip/2-htigs/split/../../../2-asm-falcon/

Do you see `p_ctg.fa`? `p_ctg.fasta`? Any `.fai`?

If you see `p_ctg.fasta.fai`, then we just need to update Unzip, which I was planning to do today anyway.

**Comment by clsaetre** [comment]
Thanks for the quick response! I see `p_ctg.fa`, but no `.fai`. Here is the content of the folder:

```
$ ls -larth 3-unzip/2-htigs/split/../../../2-asm-falcon/
total 2.8G
-rwxrwxr-x 1 clsaetre users  249 Aug 21 17:21 run-Pe8f54e4f1fef66.bash
-rw-rw-r-- 1 clsaetre users 1.7M Aug 21 17:21 contig.gfa.json
-rw-rw-r-- 1 clsaetre users  48K Aug 21 17:21 chimers_nodes
-rw-rw-r-- 1 clsaetre users  27M Aug 21 17:21 sg.gfa
-rw-rw-r-- 1 clsaetre users    0 Aug 21 17:21 falcon_asm_done
-rw-rw-r-- 1 clsaetre users 1.8M Aug 21 17:21 ctg_paths
-rw-rw-r-- 1 clsaetre users 442K Aug 21 17:21 contig.gfa2
-rw-rw-r-- 1 clsaetre users  17M Aug 21 17:21 asm.gfa2
-rw-rw-r-- 1 clsaetre users 132M Aug 21 17:21 asm.gfa.json
-rw-rw-r-- 1 clsaetre users 270M Aug 21 17:21 sg.gfa.json
-rw-rw-r-- 1 clsaetre users 1.3M Aug 21 17:21 a_ctg_tiling_path
-rw-rw-r-- 1 clsaetre users 2.1K Aug 21 17:21 user_script.sh
-rw-rw-r-- 1 clsaetre users    0 Aug 21 17:21 run.sh.done
-rw-rw-r-- 1 clsaetre users 1.2G Aug 21 17:21 p_ctg.fa
-rw-rw-r-- 1 clsaetre users 169K Aug 21 17:21 fc_ovlp_to_graph.log
-rw-rw-r-- 1 clsaetre users 146M Aug 21 17:21 a_ctg.fa
-rw-rw-r-- 1 clsaetre users 6.7M Aug 21 17:21 a_ctg_all_tiling_path
-rw-rw-r-- 1 clsaetre users 2.0K Aug 21 17:21 template.sh
-rw-rw-r-- 1 clsaetre users 118M Aug 21 17:21 sg_edges_list
-rw-rw-r-- 1 clsaetre users 2.9K Aug 21 17:21 run-Pe8f54e4f1fef66.bash.stdout
-rw-rw-r-- 1 clsaetre users 5.1M Aug 21 17:21 run-Pe8f54e4f1fef66.bash.stderr
lrwxrwxrwx 1 clsaetre users   45 Aug 21 17:21 preads4falcon.fasta -> ../1-preads_ovl/db2falcon/preads4falcon.fasta
-rw-rw-r-- 1 clsaetre users 2.5M Aug 21 17:21 c_path
-rw-rw-r-- 1 clsaetre users  16M Aug 21 17:21 asm.gfa
-rw-rw-r-- 1 clsaetre users  15M Aug 21 17:21 utg_data
-rw-rw-r-- 1 clsaetre users  576 Aug 21 17:21 task.sh
-rw-rw-r-- 1 clsaetre users  35M Aug 21 17:21 sg.gfa2
-rw-rw-r-- 1 clsaetre users  197 Aug 21 17:21 run.sh
-rw-rw-r-- 1 clsaetre users  738 Aug 21 17:21 task.json
-rw-rw-r-- 1 clsaetre users 672M Aug 21 17:21 a_ctg_all.fa
-rw-rw-r-- 1 clsaetre users 148M Aug 21 17:21 preads.ovl
drwxrwxr-x 2 clsaetre users   32 Aug 21 17:21 .
-rw-rw-r-- 1 clsaetre users  13M Aug 21 17:21 p_ctg_tiling_path
drwxrwxr-x 9 clsaetre users   55 Aug 30 05:23 ..
```

**Comment by pb-cdunn** [comment]
Yes, we'll update today. There wasn't time over weekend.

**Comment by pb-cdunn** [comment]
This should be fixed. Please re-open if not.

**Comment by clsaetre** [comment]
I'm sorry, but it's still not working. I ran conda update --all and then submitted the script again without deleting anything. I now see `p_ctg.fasta.fai` in 2-asm-falcon, but the error seems to be something else. Here is part of 3-unzip/2-htigs/split/run-P5d086c1c3f99ae.bash.stderr:

```
2019-09-06 08:15:22,603 - root - DEBUG - Running "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py /work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/task.json"
2019-09-06 08:15:22,608 - root - DEBUG - Checking existence of '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/task.json' with timeout=30
2019-09-06 08:15:22,608 - root - DEBUG - Loading JSON from '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/task.json'
2019-09-06 08:15:22,611 - root - DEBUG - {'bash_template_fn': 'template.sh',
 'inputs': {'falcon_asm_done': '../../../2-asm-falcon/falcon_asm_done',
            'gathered_rid_to_phase': '../../0-phasing/gathered-rid-to-phase/gathered.json',
            'p_ctg': '../../1-hasm/p_ctg.fasta',
            'preads4falcon': '../../../1-preads_ovl/db2falcon/preads4falcon.fasta',
            'rid_to_phase_all': '../../1-hasm/concatenated-rid-to-phase/rid_to_phase.all'},
 'outputs': {'bash_template': 'dummy.sh', 'split': 'all-units-of-work.json'},
 'parameters': {'pypeflow_mb': '393216',
                'pypeflow_nproc': '64',
                'topdir': '../../..'}}
2019-09-06 08:15:22,611 - root - INFO - CD: '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split' <- '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split'
2019-09-06 08:15:22,611 - root - DEBUG - Checking existence of '../../../2-asm-falcon/falcon_asm_done' with timeout=30
2019-09-06 08:15:22,612 - root - DEBUG - Checking existence of '../../0-phasing/gathered-rid-to-phase/gathered.json' with timeout=30
2019-09-06 08:15:22,613 - root - DEBUG - Checking existence of '../../1-hasm/p_ctg.fasta' with timeout=30
2019-09-06 08:15:52,658 - root - ERROR - Was waiting for '../../1-hasm/p_ctg.fasta'
Traceback (most recent call last):
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 69, in wait_for
    _wait_for(fn, timeout)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 85, in _wait_for
    raise Exception('Timed out waiting for {!r}'.format(fn))
Exception: Timed out waiting for '../../1-hasm/p_ctg.fasta'
2019-09-06 08:15:52,663 - root - INFO - CD: '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split' -> '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split'
2019-09-06 08:15:52,664 - root - CRITICAL - Error in /usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/work/users/clsaetre/falcon_unzip/3-unzip/2-htigs/split/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 219, in run_cfg_in_tmpdir
    wait_for(fn)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 69, in wait_for
    _wait_for(fn, timeout)
  File "/usit/abel/u1/clsaetre/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 85, in _wait_for
    raise Exception('Timed out waiting for {!r}'.format(fn))
Exception: Timed out waiting for '../../1-hasm/p_ctg.fasta'

```

In 1-hasm I see `p_ctg.fa`, but not `p_ctg.fasta`.

Thank you for your assistance!

**Comment by pb-cdunn** [comment]
We have tried to add backward-compatibility between a new Unzip run and an older Falcon run, but your problem seems to be in resuming an Unzip run. We _try_ to make that possible, but this particular change (forced on us for PB-specific reasons) made that difficult. So you would need to re-run the whole Unzip (3- and 4- directories) if you update your software. If you really need to resume, you could try symlinking the missing files. (`.fa` has been renamed to `.fasta`, and you may need to worry about `.fasta.fai` files too.)

But for a fresh run, this is what we see:
```
r% ls 1-hasm/
a_ctg_all.fasta            ctg_paths          preads4falcon.fasta              run.sh         task.sh
a_ctg_all_tiling_path      fc.log             run-P39fc18b8dd89ac.bash         run.sh.done    template.sh
concatenated-rid-to-phase  p_ctg.fasta        run-P39fc18b8dd89ac.bash.stderr  sg_edges_list  user_script.sh
c_path                     p_ctg_tiling_path  run-P39fc18b8dd89ac.bash.stdout  task.json      utg_data
```
That is with the latest Bioconda. I do not think it is possible that the `1-hasm` directory is populated with `.fa` files with the latest code.

```
% conda list
pb-assembly               0.0.6                    py37_5    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 2.2.0            py37hed50d52_0    bioconda

% python3
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import falcon_kit
falcon-kit 1.5.2 (pip thinks "falcon-kit 1.5.2")
>>> import falcon_unzip
falcon-unzip 1.3.5 (pip thinks "falcon-unzip 1.3.5")
```

**Comment by zeeev** [comment]
hi @clsaetre,

Apologies for the inconvenience. I too had a few unzip runs that were affected by the necessary code update. Chris correctly points out that you can just do a fresh `3-unzip` run, but if you're like me and don't want to repeat the work, here's the code snipped I used to soft-link the missing files and move forward. 


`find 3-unzip/0-phasing/ | grep "ref.fa" | perl -lane '$_ =~ s/\/ref.fa//; print' | xargs -I {} readlink -f {} | perl -lane 'print "cd $_ ; ln -s ref.fa ref.fasta"' | xargs -I {} bash -c {}`

**Comment by clsaetre** [comment]
Great! Thank you both so much!

All the best,
Camilla

**Comment by A-J-F-Mackintosh** [comment]
Hi @pb-cdunn,

I am having a similar problem to @clsaetre even though I have the most recent bioconda release of falcon and falcon-unzip.

`falcon-unzip 1.3.5 (pip thinks "falcon-unzip 1.3.5")
falcon-kit 1.5.2 (pip thinks "falcon-kit 1.5.2")`

Falcon-unzip ended with the following error:

`[ERROR]Task Node(3-unzip/2-htigs/split) failed with exit-code=1`

And looking in the file `/3-unzip/2-htigs/split/run-P542f24f3c47cb6.bash.stderr` I found the following:

`FileNotFoundError: [Errno 2] No such file or directory: '../../../2-asm-falcon/p_ctg.fasta.fai'`

This exact file does exist in `2-asm-falcon`, so my guess is that the relative path is incorrect but I am not sure.

Any help finding the source of the error would be really appreciated.

Best,

Alex

**Comment by pb-cdunn** [comment]
Are you sure you're up-to-date? Some folks are on python2.7, so they don't get our updates, which are only for python3.7 now.

The latest falcon code definitely creates `2-asm-falcon/p_ctg.fasta.fai`; I'm looking right at it!
