### ISSUE TITLE
Error at the 4-quiver step of pb-assembly

### ISSUE THREAD

**Issue by a-velt** [PacificBiosciences/pbbioconda#21]
**Operating system**
Linux 2.6.32-696.16.1.el6.x86_64 - Scientific Linux release 6.9 (Carbon)

**Package name**
I installed the last version of pb-assembly (version 0.0.0) with conda. I have a bug with fc_quiver.py script.

**Conda environment**

```
# packages in environment at /cm/shared/apps/FALCON_12_09_2018:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0
avro                      1.8.0                    py27_0    bioconda
bcftools                  1.9                  h4da6232_0    bioconda
blas                      1.0                         mkl
blasr                     5.3.2                hac9d22c_3    bioconda
blasr_libcpp              5.3.1                hac9d22c_2    bioconda
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py27_1    conda-forge
cffi                      1.11.5           py27he75722e_1
chardet                   3.0.4                    py27_1
conda                     4.5.11                   py27_0    conda-forge
conda-env                 2.6.0                         1
cryptography              2.3.1            py27hc365091_0
curl                      7.61.0               h93b3f91_2    conda-forge
cython                    0.28.5           py27hfc679d8_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
enum34                    1.1.6                    py27_1
future                    0.16.0                   py27_2    conda-forge
futures                   3.2.0                    py27_0
genomicconsensus          2.3.2                    py27_1    bioconda
h5py                      2.8.0            py27hb794570_1    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
htslib                    1.7                           0    bioconda
idna                      2.7                      py27_0
intel-openmp              2018.0.3                      0
ipaddress                 1.0.22                   py27_0
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
linecache2                1.0.0                    py27_0    conda-forge
minimap2                  2.12                 ha92aebf_0    bioconda
mkl                       2018.0.3                      1
mkl_fft                   1.0.6                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
mummer                    3.23                    pl526_6    bioconda
ncurses                   6.1                  hf484d3e_0
networkx                  2.1                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.15.1           py27h1d66e8a_0
numpy-base                1.15.1           py27h81de0dd_0
openssl                   1.0.2p               h470a237_0    conda-forge
pb-assembly               0.0.0                    py27_3    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.0.2                    py27_0    bioconda
pbalign                   0.3.1                    py27_0    bioconda
pbbam                     0.18.0               h1310cd9_1    bioconda
pbcommand                 1.1.1            py27h24bf2e0_1    bioconda
pbcore                    1.5.1                    py27_1    bioconda
perl                      5.26.2               h470a237_0    conda-forge
pip                       10.0.1                   py27_0
pycosat                   0.6.3            py27h14c3975_0
pycparser                 2.18                     py27_1
pyopenssl                 18.0.0                   py27_0
pysam                     0.14.1           py27hae42fb6_1    bioconda
pysocks                   1.6.8                    py27_0
python                    2.7.15               h1571d57_0
python-consensuscore      1.1.1            py27h02d93b8_1    bioconda
python-consensuscore2     3.1.0                    py27_1    bioconda
python-edlib              1.2.3            py27h470a237_1    bioconda
python-intervaltree       2.1.0                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.0.4                      py_0    bioconda
pytz                      2018.5                     py_0    conda-forge
readline                  7.0                  h7b6447c_5
requests                  2.19.1                   py27_0
ruamel_yaml               0.15.46          py27h14c3975_0
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.2.0                   py27_0
six                       1.11.0                   py27_1
sqlite                    3.24.0               h84994c4_0
tk                        8.6.8                hbc83047_0
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.23                     py27_0
wheel                     0.31.1                   py27_0
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                had09818_2
zlib                      1.2.11               ha838bed_2
```

**Describe the bug**

The step "3-unzip" of pb-assembly works well, with the files "all_p_ctg.fa" and "all_h_ctg.fa" generated, but quiver step doesn't work. I have the impression that it is having an error at the end. Have you ever met this?

Here the folder 4-quiver. The last step that has worked seems to be quiver-run : 
<img width="164" alt="quiver" src="https://user-images.githubusercontent.com/23554476/46000932-49354000-c0aa-11e8-84d4-6dfc7e5e001e.PNG">

There are 2639 folders in quiver-run, so there are steps that have worked, but not all.

**Error message**

Here the log with the error : 
```
 [INFO]Popen: 'bash -C /cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/run-P11ad2b39cd9e4b.bash
 .stdout 2>| /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/run-P11ad2b39cd9e4b.bash.stderr'
 [ERROR]Task Node(4-quiver/quiver-run/000153Fp01_00001) failed with exit-code=1
 [ERROR]Some tasks are recently_done but not satisfied: set([Node(4-quiver/quiver-run/000153Fp01_00001)])
 [ERROR]ready: set([Node(4-quiver/quiver-run/001238Fp01_00002), Node(4-quiver/quiver-run/000889Fp01), Node(4-quiver/quiver-run/000200Fp01), Node(4-quiver/quiver-run/002254Fp02), Node(4-quiver/quiver-run/001827
 Fp01), Node(4-quiver/quiver-run/000342Fp01), Node(4-quiver/quiver-run/000474Fp01), Node(4-quiver/quiver-run/000078Fp01_00001), Node(4-quiver/quiver-run/001592Fp01_00001), Node(4-quiver/quiver-run/001250Fp01),
  Node(4-quiver/quiver-run/000682Fp01), Node(4-quiver/quiver-run/001979Fp01), Node(4-quiver/quiver-run/001033Fp01_00001), Node(4-quiver/quiver-run/000477Fp01), Node(4-quiver/quiver-run/000495Fp01), Node(4-quiv
 er/quiver-run/002699Fp01), Node(4-quiver/quiver-run/000450Fp01_00001), Node(4-quiver/quiver-run/001441Fp01), Node(4-quiver/quiver-run/000209Fp01), Node(4-quiver/quiver-run/000584Fp01_00001), Node(4-quiver/qui
 ...................
 ver-run/000645Fp01), Node(4-quiver/quiver-run/000637Fp01), Node(4-quiver/quiver-run/000408Fp01_00003), Node(4-quiver/quiver-run/000176Fp01_00001), Node(4-quiver/quiver-run/002065Fp01), Node(4-quiver/quiver-ru
 n/000405Fp01_00002), Node(4-quiver/quiver-run/000675Fp01_00001), Node(4-quiver/quiver-run/000735Fp01_00001), Node(4-quiver/quiver-run/002196Fp02), Node(4-quiver/quiver-run/000743Fp01), Node(4-quiver/quiver-ru
 n/000559Fp01_00001), Node(4-quiver/quiver-run/000317Fp01_00002)])
         submitted: set([Node(4-quiver/quiver-run/000484Fp01_00001)])
 [ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
 Traceback (most recent call last):
   File "/cm/shared/apps/FALCON_12_09_2018/bin//fc_quiver.py", line 11, in <module>
     load_entry_point('falcon-unzip==1.1.2', 'console_scripts', 'fc_quiver.py')()
   File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 29, in main
     unzip.run(**vars(args))
   File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 126, in run
     unzip_all(config)
   File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 28, in unzip_all
     tasks_unzip.run_workflow(wf, config, rule_writer)
   File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 708, in run_workflow
    job_dict=config['job.step.unzip.quiver'],
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_kit/pype.py", line 192, in gen_parallel_tasks
     wf.refreshTargets()
   File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
     self._refreshTargets(updateFreq, exitOnFailure)
   File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 361, in _refreshTargets
     raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(4-quiver/quiver-run/000153Fp01_00001)])
make: *** [quiver] Error 1
```

Here the "4-quiver/quiver-run/000153Fp01_00001/run-P11ad2b39cd9e4b.bash.stderr" file : 

```
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/run-P11ad2b39cd9e4b.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/run-P11ad2b39cd9e4b.bash ]]

/bin/bash ${executable}
+ /bin/bash /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/run-P11ad2b39cd9e4b.bash
+ '[' '!' -d /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001 ']'
+ cd /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
export PATH=$PATH:/bin
+ export PATH=/cm/shared/apps/FALCON_12_09_2018/bin/:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/slurm/14.03.0/sbin:/cm/shared/apps/slurm/14.03.0/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbi
n:/cm/local/apps/cmd/bin:/cm/shared/apps/cmgui:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/root/bin:/bin
+ PATH=/cm/shared/apps/FALCON_12_09_2018/bin/:/cm/shared/apps/Perl_conda/bin:/cm/shared/apps/slurm/14.03.0/sbin:/cm/shared/apps/slurm/14.03.0/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbin:/cm/l
ocal/apps/cmd/bin:/cm/shared/apps/cmgui:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/root/bin:/bin
cd /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001
+ cd /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001
/bin/bash task.sh
+ /bin/bash task.sh
pypeflow 2.0.4
2018-09-25 01:34:24,412 - root - DEBUG - Running "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/task.js
on"
2018-09-25 01:34:24,414 - root - DEBUG - Checking existence of '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/task.json' with timeout=30
2018-09-25 01:34:24,414 - root - DEBUG - Loading JSON from '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001/task.json'
2018-09-25 01:34:24,415 - root - DEBUG - {u'bash_template_fn': u'template.sh',
 u'inputs': {u'bash_template': u'/data2/avelt/Assembly_amurensis/4-quiver/quiver-split/bash-template.sh',
             u'units_of_work': u'/data2/avelt/Assembly_amurensis/4-quiver/quiver-chunks/000153Fp01_00001/some-units-of-work.json'},
 u'outputs': {u'results': u'results.json'},
 u'parameters': {u'pypeflow_mb': 4000, u'pypeflow_nproc': u'5'}}
2018-09-25 01:34:24,415 - root - WARNING - CD: '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001' <- '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001'
2018-09-25 01:34:24,415 - root - DEBUG - Checking existence of u'/data2/avelt/Assembly_amurensis/4-quiver/quiver-chunks/000153Fp01_00001/some-units-of-work.json' with timeout=30
2018-09-25 01:34:24,416 - root - DEBUG - Checking existence of u'/data2/avelt/Assembly_amurensis/4-quiver/quiver-split/bash-template.sh' with timeout=30
2018-09-25 01:34:24,416 - root - DEBUG - Checking existence of u'template.sh' with timeout=30
2018-09-25 01:34:24,416 - root - WARNING - CD: '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001' <- '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001'
2018-09-25 01:34:24,417 - root - INFO - $('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
# Substitution will be similar to snakemake "shell".
python -m falcon_kit.mains.generic_run_units_of_work --nproc=5 --units-of-work-fn=/data2/avelt/Assembly_amurensis/4-quiver/quiver-chunks/000153Fp01_00001/some-units-of-work.json --bash-template-fn=/data2/avel
t/Assembly_amurensis/4-quiver/quiver-split/bash-template.sh --results-fn=results.json
+ python -m falcon_kit.mains.generic_run_units_of_work --nproc=5 --units-of-work-fn=/data2/avelt/Assembly_amurensis/4-quiver/quiver-chunks/000153Fp01_00001/some-units-of-work.json --bash-template-fn=/data2/av
elt/Assembly_amurensis/4-quiver/quiver-split/bash-template.sh --results-fn=results.json
falcon-kit 1.2.2
pypeflow 2.0.4
INFO:root:INPUT:{u'ref_fasta': u'/data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa', u'read_bam': u'/data2/avelt/Assembly_amurensis/4-quiver/segregate-run/segr1905/segregate
d/000153Fp01_00001/000153Fp01_00001.bam', u'ctg_type': u'/data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ctg_type'}
INFO:root:OUTPUT:{u'cns_fasta': u'cns.fasta.gz', u'cns_vcf': u'cns.vcf', u'job_done': u'quiver_done', u'ctg_type_again': u'ctg_type', u'cns_fastq': u'cns.fastq.gz'}
INFO:root:PARAMS:{'pypeflow_nproc': '5', u'ctg_id': u'000153Fp01_00001'}
INFO:root:$('rm -rf uow-00')
WARNING:root:CD: 'uow-00' <- '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001'
INFO:root:$('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
set -vex
+ set -vex
trap 'touch quiver_done.exit' EXIT
+ trap 'touch quiver_done.exit' EXIT
hostname
+ hostname
date
+ date

samtools faidx /data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa
+ samtools faidx /data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa
[faidx] Could not build fai index /data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa.fai
touch quiver_done.exit
+ touch quiver_done.exit
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001'
Traceback (most recent call last):
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 115, in <module>
    main()
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 111, in main
    run(**vars(args))
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 64, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py", line 178, in run_bash
    util.system(cmd)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2018-09-25 01:34:24,870 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2018-09-25 01:34:24,870 - root - WARNING - CD: '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001' -> '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001'
2018-09-25 01:34:24,870 - root - WARNING - CD: '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001' -> '/data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001'
2018-09-25 01:34:24,870 - root - CRITICAL - Error in /cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/data2/avelt/Assembly_amurensis/4-quiver/quiver-r
un/000153Fp01_00001/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py", line 246, in <module>
    main()
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py", line 238, in main
    run(**vars(parsed_args))
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py", line 232, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py", line 208, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/do_task.py", line 178, in run_bash
    util.system(cmd)
  File "/cm/shared/apps/FALCON_12_09_2018/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /data2/avelt/Assembly_amurensis/4-quiver/quiver-run/000153Fp01_00001 (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get
diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real    0m1.432s
user    0m0.327s
sys     0m0.164s
+ finish
+ echo 'finish code: 1'

```

**To Reproduce**
I give you the two fasta files at the end of the 3-unzip step, are they enough?
https://www.dropbox.com/s/l5n2gu2etdhkute/3-unzip.zip?dl=0

**Expected behavior**
I expect that two polished fasta files must be generate, one for primary contigs and one for haplotigs.

Best,
Amandine

**Comment by pb-cdunn** [comment]
```
+ samtools faidx /data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa
[faidx] Could not build fai index /data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa.fai
```
Could you add that `ref.fa` to dropbox? Or is that file empty? If it's short, just post it here.

**Comment by pb-cdunn** [comment]
After you look at that `ref.fa`, note that you are using an old `pb-assembly/pb-falcon`. Try updating, re-post `conda list`, and re-run.

But look at `ref.fa` first. We are curious about the actual crash.

**Comment by a-velt** [comment]
Hi,

Thank you for your help. There is juste the header in the ref.fa file : 
`more /data2/avelt/Assembly_amurensis/4-quiver/quiver-split/./refs/000153Fp01_00001/ref.fa`

`>000153Fp01_00001`

I launched: 
`conda update pb-assembly`

And now the conda list : 
```
# packages in environment at /cm/shared/apps/FALCON_12_09_2018:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0
avro                      1.8.0                    py27_0    bioconda
bcftools                  1.9                  h4da6232_0    bioconda
bedtools                  2.27.1               he941832_2    bioconda
blas                      1.0                         mkl
blasr                     5.3.2                hac9d22c_3    bioconda
blasr_libcpp              5.3.1                hac9d22c_2    bioconda
bwa                       0.7.17               ha92aebf_3    bioconda
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24             py27_1001    conda-forge
cffi                      1.11.5           py27he75722e_1
chardet                   3.0.4                    py27_1
conda                     4.5.11                   py27_0    conda-forge
conda-env                 2.6.0                         1
cryptography              2.3.1            py27hc365091_0
curl                      7.61.0               h93b3f91_2    conda-forge
cython                    0.28.5           py27hfc679d8_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
enum34                    1.1.6                    py27_1
future                    0.16.0                   py27_2    conda-forge
futures                   3.2.0                    py27_0
genomicconsensus          2.3.2                    py27_1    bioconda
h5py                      2.8.0            py27hb794570_1    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
htslib                    1.7                           0    bioconda
idna                      2.7                      py27_0
intel-openmp              2018.0.3                      0
ipaddress                 1.0.22                   py27_0
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
linecache2                1.0.0                    py27_0    conda-forge
minimap2                  2.12                 ha92aebf_0    bioconda
mkl                       2018.0.3                      1
mkl_fft                   1.0.6                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
mummer                    3.23                    pl526_6    bioconda
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1                  hf484d3e_0
networkx                  2.1                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.15.1           py27h1d66e8a_0
numpy-base                1.15.1           py27h81de0dd_0
openssl                   1.0.2p               h470a237_0    conda-forge
pb-assembly               0.0.1                    py27_0    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.3            py27ha92aebf_0    bioconda
pbalign                   0.3.1                    py27_0    bioconda
pbbam                     0.18.0               h1310cd9_1    bioconda
pbcommand                 1.1.1            py27h24bf2e0_1    bioconda
pbcore                    1.5.1                    py27_1    bioconda
perl                      5.26.2               h470a237_0    conda-forge
pip                       10.0.1                   py27_0
pycosat                   0.6.3            py27h14c3975_0
pycparser                 2.18                     py27_1
pyopenssl                 18.0.0                   py27_0
pysam                     0.14.1           py27hae42fb6_1    bioconda
pysocks                   1.6.8                    py27_0
python                    2.7.15               h1571d57_0
python-consensuscore      1.1.1            py27h02d93b8_1    bioconda
python-consensuscore2     3.1.0                    py27_1    bioconda
python-edlib              1.2.3            py27h470a237_1    bioconda
python-intervaltree       2.1.0                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.0.4                      py_0    bioconda
pytz                      2018.5                     py_0    conda-forge
readline                  7.0                  h7b6447c_5
requests                  2.19.1                   py27_0
ruamel_yaml               0.15.46          py27h14c3975_0
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.2.0                   py27_0
six                       1.11.0                   py27_1
sqlite                    3.24.0               h84994c4_0
tk                        8.6.8                hbc83047_0
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.23                     py27_0
wheel                     0.31.1                   py27_0
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                had09818_2
zlib                      1.2.11               ha838bed_2
```

I will launch the 4-quiver step with the new version of pb-assembly/pb-falcon. I will keep you in touch.

Best,
Amandine

**Comment by isovic** [comment]
Hi Amandine,
The empty sequence in the `ref.fa` is peculiar...
Could you please zip and upload the contents of the `3-unzip/2-htigs/chunk_000153F` folder? Hopefully it shouldn't be too big, and we would like to take a look.

Best regards,
Ivan.

**Comment by a-velt** [comment]
Here the zip file : 
[chunk_000153F.zip](https://github.com/PacificBiosciences/pbbioconda/files/2423805/chunk_000153F.zip)

Thank you for your help.
Best,
Amandine

**Comment by a-velt** [comment]
I get the same error with the last version of pb-assembly. Maybe I need to restart the 3-unzip step with the new version too? Because here I had launched only stage 4. I will test.

**Comment by isovic** [comment]
Thank you for sharing the data!
It seems that for some reason a zero-length haplotig is being extracted, which in turn causes `samtools` to exit non-zero. We're looking into it, but for now, you could try manually removing it from `3-unzip/all_h_ctg.fa` and re-launching the 4-quiver stage.

It could also be useful for our debugging if you could also zip and send the `3-unzip/0-phasing/000153F` folder?
Best regards,
Ivan

**Comment by a-velt** [comment]
Here the 3-unzip/0-phasing/000153F folder :

[000153F.zip](https://github.com/PacificBiosciences/pbbioconda/files/2432963/000153F.zip)

I will remove it from 3-unzip/all_h_ctg.fa file and try to run 4-quiver stage, I keep you in touch.

Best,
Amandine

**Comment by a-velt** [comment]
It works by removing the sequence from 3-unzip/all_h_ctg.fa !

**Comment by isovic** [comment]
To anyone else running into this same issue:
In the latest version of Unzip we fixed a bug that could have caused empty haplotigs to be written to the FASTA file, but also provide a safeguard to prevent such haplotigs and primary contigs to be written.
This is now available in `falcon-unzip 1.1.4` available in `pb-falcon>=0.2.4` and `pb-assembly>=0.0.2`.
Note: this fix applies only if the `3-unzip` stage is re-run. If the rerun process is costly and you have completed it using an older version, please use the same workaround as @a-velt and manually filter the empty sequences from `3-unzip/all_h_ctg.fa`.

**Comment by nicolasalexandre21** [comment]
I have run into this issue as well, updated pb-assembly, falcon unzip, and pb-falcon and rerun the process from the 3-unzip step. As above, my errors still occur in the quiver-run and quiver-chunks step.

I looked for a reference file in the 4-quiver folder, but there is no quiver-split sub-folder.

Any help would be appreciated.

**Comment by nicolasalexandre21** [comment]
The output ends with the following:
Exception: Some tasks are recently_done but not satisfied: set([Node(4-polish/quiver-run/000048F_004)])

Based on this stderr file, it looks like this is the step that failed

/global/scratch/nalexandre/spikedace/4-quiver/quiver-run/000048F_004

When I look at this sequence in the 3-unzip/all_h_ctg.fa file, it is not of zero-length, so not sure what's going on.
