### ISSUE TITLE
Problem with samtools using conda : libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by Lcornet** [PacificBiosciences/pbbioconda#85]
Dear Falcon team,

I installed pb-assembly on a cluster using conda2 and i have the folloiwing error while running unzip  :

# falcon-test/3-unzip/0-phasing/002649F/run-P1e540c5b720f27.bash.stderr
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

#the channels order are configured according to : https://bioconda.github.io/index.html#set-up-channels.

Can you help me ?

**Comment by pb-cdunn** [comment]
We're not quite sure of the problem, but `conda update --all` might fix it.

Soon, we'll try to rebuild the recipes to see if that helps.

**Comment by pb-cdunn** [comment]
Actually, I don't think this is solved in all cases. It depends on what python/pyopenssl you happen to be using. I've filed a ticket with **conda-forge**, since I don't see a way to fix this strictly within **bioconda**.

https://github.com/conda-forge/conda-forge.github.io/issues/701

**Comment by Lcornet** [comment]
conda update --all don't fix it.
So i remove my conda and then reinstall everything with : conda install -c bioconda/label/cf201901 pb-assembly.

It seems to work (samtools access), i will let you know once unzip will be at 0-pahsing step if everything is fine.

**Comment by Lcornet** [comment]
A re-install of pb-assembly fix the problem of samtools.

Thanks for the help

**Comment by pb-cdunn** [comment]
Glad that worked, but it does not work for everyone. The solution which seems to work reliably is `strict` channel priority:
```
% less ~/.condarc
channels:
  - bioconda
  - conda-forge
  - defaults

channel_priority: strict
```
That would require conda >= 4.6, which is pretty recent.

**Comment by foala** [comment]
Hi Christopher and all,
I tried this approach and it worked.
**### Problem:**
1) I installed the latest pb-assembly (pb-assembly:  0.0.4-py27_5).
2) I got this error when I ran $ fc_unzip.py fc_unzip.cfg:

`[ERROR]samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

---
Could not discern version of samtools. We need at least 1.3.0. Good luck!`
and got this in my quiver-run filers:
```
samtools faidx ../../../quiver-split/refs/000066F_034/ref.fa
+ samtools faidx ../../../quiver-split/refs/000066F_034/ref.fa
**samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory**
``` 
3) My conda list result:
`# packages in environment at /home/farooq/Software/anaconda3/envs/falcon:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  h47928c2_2    bioconda
bedtools                  2.27.1               he860b03_3    bioconda
blas                      1.0                         mkl
blasr                     5.3.2                h82bacf8_5    bioconda
blasr_libcpp              5.3.1                h82bacf8_4    bioconda
bwa                       0.7.17               h84994c4_5    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.12.2           py27h9745a5d_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.5              py27h9d9f1b6_1    conda-forge
curl                      7.64.0               h646f8bb_2    conda-forge
cython                    0.29.6           py27hf484d3e_0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
future                    0.17.1                py27_1000    conda-forge
genomicconsensus          2.3.2                    py27_3    bioconda
h5py                      2.8.0           py27hfb8609e_1004    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
htslib                    1.9                  h47928c2_5    bioconda
idna                      2.8                   py27_1000    conda-forge
intel-openmp              2019.1                      144
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libcurl                   7.64.0               h541490c_2    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0             h90d6eec_1004    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.16                 h84994c4_1    bioconda
mkl                       2019.1                      144
mkl_fft                   1.0.10           py27h14c3975_1    conda-forge
mkl_random                1.0.2            py27h637b7d7_2    conda-forge
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1                  he6710b0_1
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.16.2           py27h7e9f1db_0
numpy-base                1.16.2           py27hde5b4d6_0
openssl                   1.1.1b               h14c3975_0    conda-forge
pb-assembly               0.0.4                    py27_5    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.6            py27hc0aa232_3    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.19.0               h6678c95_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbmm2                     0.12.0               ha87ae23_0    bioconda
perl                      5.26.2            h14c3975_1002    conda-forge
pip                       19.0.3                   py27_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.2           py27h1671916_1    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h721da81_1008    conda-forge
python-consensuscore      1.1.1            py27h02d93b8_2    bioconda
python-consensuscore2     3.1.0                    py27_2    bioconda
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
samtools                  1.9                  h91753b0_5    bioconda
setuptools                40.8.0                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wheel                     0.33.1                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge`
 

**and the priorty channel is conda-forge**

### **Solution**
1) I replaced the current build of ncurses with an older one:
`conda install -c conda-forge ncurses=6.1=he6710b0_1`
2) I replaced the current version of openssl with an older one as follows:
`conda install -c conda-forge openssl=1.0.2p=h14c3975_1002`
3) Now, when I run unzip, the problem is solved:
`[INFO]$ samtools >
[INFO]samtools ['1', '9'] is >= 1.3
`

I would like your input, and whether this is the right approach.
Thank you,

**Comment by pb-cdunn** [comment]
No, it's a terrible approach, but it might be the best available today.

I am hoping that Bioconda folks will resolve this problem reliably. But I will mention your work-around. Thanks!

**Comment by foala** [comment]
Hi Chris,
I am interested in using the "polish using all subreads' feature in the latest release. Does this way, being terrible!, affect the end result?
Thanks!

**Comment by pb-cdunn** [comment]
It's sometimes possible to improve polishing by including all subreads. It depends.

**Comment by pb-cdunn** [comment]
Try again. All our problems with this seem to have been solved by https://github.com/bioconda/bioconda-recipes/issues/13958

**Comment by RNieuwenhuis** [comment]
This problem is either back or not completely resolved yet.

`conda --version`
`conda 4.6.11`

'''
conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at ~/miniconda3/envs/GenomicConsensus:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  ha228f0b_3    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py27_0    conda-forge
cffi                      1.12.2           py27hf0e25f4_1    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.6.1            py27h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cython                    0.29.6           py27hf484d3e_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
genomicconsensus          2.3.3                    py27_0    bioconda
h5py                      2.9.0           nompi_py27hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
idna                      2.8                   py27_1000    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
linecache2                1.0.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.2           py27h7fc5cc3_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pbcommand                 1.1.1                    py27_2    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pip                       19.0.3                   py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.2           py27h4b7d16d_3    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h721da81_1008    conda-forge
python-consensuscore      1.1.1            py27h3f2a3d2_3    bioconda
python-consensuscore2     3.4.1                    py27_0    bioconda
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.0                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wheel                     0.33.1                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
'''
So I created a fresh environment using `conda create -n GenomicConsensus`
Then after activating the environment, `conda install GenomicConsensus`

`which samtools` returns `~/miniconda3/envs/GenomicConsensus/bin/samtools`

And:
'''
samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
'''

However samtools does not work correctly:
`samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`


I guessed that all the troubles regarding samtools and openssl were solved. Updating samtools gives no updates found. So is there anything I've missed in all the other threads of pbbioconda and bioconda?

**Comment by pb-cdunn** [comment]
It's still working fine for me with exactly the same env (afaict). Possibly you have `LD_LIBRARY_PATH` set to skip the conda-env shared libraries. Try this:
```
which samtools

ldd $(which samtools)
```
I have this:
```
% which samtools
~/.conda/envs/pb-2.7/bin/samtools

% ldd $(which samtools)
        linux-vdso.so.1 =>  (0x00007ffcea581000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9b549cb000)
        libz.so.1 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libz.so.1 (0x00007f9b549b0000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9b546ae000)
        libbz2.so.1.0 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libbz2.so.1.0 (0x00007f9b5469a000)
        liblzma.so.5 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/liblzma.so.5 (0x00007f9b54670000)
        libdeflate.so => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libdeflate.so (0x00007f9b54660000)
        libcurl.so.4 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libcurl.so.4 (0x00007f9b545d8000)
        libcrypto.so.1.1 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libcrypto.so.1.1 (0x00007f9b542df000)
        libncursesw.so.6 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libncursesw.so.6 (0x00007f9b542a3000)
        libtinfow.so.6 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/libtinfow.so.6 (0x00007f9b54266000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9b53ea2000)
        /lib64/ld-linux-x86-64.so.2 (0x000056357c1f7000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9b53c9a000)
        libssh2.so.1 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/./libssh2.so.1 (0x00007f9b53c66000)
        libssl.so.1.1 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/./libssl.so.1.1 (0x00007f9b53bd0000)
        libgssapi_krb5.so.2 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/./libgssapi_krb5.so.2 (0x00007f9b53b81000)
        libkrb5.so.3 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/./libkrb5.so.3 (0x00007f9b53aa4000)
        libk5crypto.so.3 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/./libk5crypto.so.3 (0x00007f9b53a85000)
        libcom_err.so.3 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/./libcom_err.so.3 (0x00007f9b53a7f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9b5387a000)
        libkrb5support.so.0 => /home/UNIXHOME/cdunn/.conda/envs/pb-2.7/bin/../lib/././libkrb5support.so.0 (0x00007f9b5386b000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f9b53650000)
```
Maybe you can debug this by comparing. If not, you might need to file a ticket with the Bioconda team somehow. Or comment in "https://github.com/bioconda/bioconda-recipes SLASH issues SLASH 13958"

There is only so much we can do. This was a problem for PB people internally, but not anymore.

**Comment by ajaz240792** [comment]
You can create a symbolic link to the libcrypto.*

**Comment by pb-dseifert** [comment]
Symlinking shared objects with different SONAMEs is absolutely wrong and is likely to cause more issues that it solves. This probably only requires a conda env update or a fresh conda install.

**Comment by shahramsaghaei** [comment]
If you are using a conda env, simply use 

    conda install -c bioconda samtools openssl=1.0
